### ISSUE TITLE
Unable to scroll Shapeshift list with mouse wheel

### ISSUE THREAD

**Issue by msuguy71** [ffMathy/Shapeshifter#160]
I tried using the mouse wheel to scroll through the Shapeshifter list, but it did not work.  I can use the arrow keys on the keyboard, or left click on the choice I want (saw this feature in a video of Shapeshifter posted in the Lifehacker comments section).  I have a Logitech G502 Proteus Core Spectrum running version 8.83.85 of their gaming software control panel.

**Comment by ffMathy** [comment]
Fixed. Will be released when #162 is merged to `master`.

**Comment by msuguy71** [comment]
The UI still doesn't scroll with my mouse wheel?  Am I doing something wrong, or is there a setting I have enable?

**Comment by ffMathy** [comment]
Is your mouse over the UI when you scroll? Are you on a laptop or a desktop?

**Comment by msuguy71** [comment]
Yeah, I am over the UI.  I can click on it and select, but not mouse wheel it.  I am on a desktop and I use the Logitech G502

**Comment by ffMathy** [comment]
Can you try with a laptop mousepad using 2 finger scroll? Because it works for me. Also, try disabling Microgear on your mouse.
