### ISSUE TITLE
Ctrl key remains active

### ISSUE THREAD

**Issue by msuguy71** [ffMathy/Shapeshifter#167]
Since releasing version 6.1.1919, the ctrl key remains active, until the ctrl key is pressed again, after pasting.  It might release after a certain amount of time, I cannot remember.  I think this may have to do with the new UI delay introduced.

**Comment by ffMathy** [comment]
Ah, that makes sense! I didn't even notice that for some reason. I will create a unit test that makes sure this doesn't happen again, and resolve the issue.

**Comment by ffMathy** [comment]
Note to self: It might be that a delay after hiding the Shapeshifter UI might be enough, and that a delay between keystrokes isn't needed.

**Comment by ffMathy** [comment]
This has been fixed, but another bug has been re-opened (the Steam one). I will try to make a fix that can fix both issues at the same time.

**Comment by thegabriestein** [comment]
I'm still experiencing this, and will need to gather data on occurrences. Seems like it occurs whenever the program lags to paste.

**Comment by ffMathy** [comment]
Hmmm very interesting. I experienced it too yesterday, but only when Shapeshifter also crashed. Is that the same for you?

**Comment by ffMathy** [comment]
This hasn't happened for me again since the latest couple of releases. Closing until we find it again.

If someone finds something, please post your logs.
