### ISSUE TITLE
Double Ctrl V required to paste

### ISSUE THREAD

**Issue by svenjochems** [ffMathy/Shapeshifter#464]
In the latest prerelease (6.2018.513.2696) I have the issue that 2 Ctrl V actions are required to paste (1 on 2 is skipped)

To reproduce (tested with normal text from notepad) :
1. Press Ctrl C to copy something
2. Press Ctrl V to paste (nothing happens)
3. Press Ctrl V again (item is pasted)

Log as attachment
[Shapeshifter20180514.log](https://github.com/ffMathy/Shapeshifter/files/1999907/Shapeshifter20180514.log)

**Comment by ffMathy** [comment]
What happens if you wait some time before pasting initially?

I think you may have found a timing related bug.

**Comment by svenjochems** [comment]
Same issue when I wait 5 seconds between pastes.

The log shows 4 paste actions, only 2 and 4 do actual pasting
The third Ctrl V seems to block something though, my cursor stopped blinking for a few seconds in notepad.

Log
[Shapeshifter20180514.log](https://github.com/ffMathy/Shapeshifter/files/2000065/Shapeshifter20180514.log)

**Comment by ffMathy** [comment]
Very interesting! I believe this could be caused by the clipboard counter overlay window stealing focus under some circumstances while the paste is being performed!

Perhaps hiding that form before paste is a good idea.

**Comment by KoalaBear84** [comment]
Cannot reproduce it on the newest version.

**Comment by svenjochems** [comment]
Still having this issue with the latest release.
I notices an Exception during installation though, maybe that is related to this.
Exception seems to be submitted as issue #492

**Comment by ffMathy** [comment]
That exception is not related. I'll try harder to reproduce this, but could use some help in determining what conditions cause it.

**Comment by svenjochems** [comment]
Things I did:
1. Install shapeshifter
2. Shapeshifter throws exception #492
3. Launch shapeshifter manually from programmes
4. Open notepad++
5. Copy something
6. Ctrl V => no paste
7. Ctrl V => paste

This does not happen randomly but all the time.
OS: win10
I do also have shapeshifter v5 installed which I normally use but I shut it down before installation of v6.

I'll be happy to provide more information if needed.

**Comment by ffMathy** [comment]
I fixed that error, and I greatly improved the logging. A new pre-release will be ready soon with this.

What is interesting to me is that it happens all the time though.

**Comment by svenjochems** [comment]
Unfortunately this problem still persists in the latest pre-release.
But it seems like I'm the only one having this issue so maybe there is something wrong on my side.
I'll try to install Shapeshifter on another PC this weekend to see if I can reproduce it there.

**Comment by ffMathy** [comment]
Yes, it will still happen, but logging has greatly improved. Please send the latest logs right after it happened.

**Comment by ffMathy** [comment]
I think I may have resolved it now. Prerelease coming up. If not, please keep reporting back - your issue is important to me, and I if you are having it, so are others :+1:

**Comment by svenjochems** [comment]
In the latest prerelease I'm still having this issue but I think I've narrowed down the cause.
I've modified the paste duration settings to 100ms.
This issue does not happen with the default of 200ms.

**Comment by ffMathy** [comment]
Aha! Very interesting. I'll try with a lower setting myself to see if that helps reproduce it.

**Comment by ffMathy** [comment]
Good news! I can now reproduce this pretty consistently!
